"""Is the generated husky machinery in this checkout what husky installs?

`tests/test_hook_integration.py` starts *after* husky: it invokes
``.husky/<hook>`` directly, so every test there passes even if the layer husky
owns is wrong. That layer is:

    git  ->  .husky/_/<hook>  ->  .husky/_/h  ->  .husky/<hook>

If `.husky/_/` was generated by a different husky version, edited by hand, or
left behind by a husky whose shim format has since changed, git runs something
this repository never intended -- and nothing else in the suite notices.

So this module does not describe the expected files. It asks husky to generate
them, in a throwaway repository, and compares byte for byte with the ones on
disk. The expectation therefore stays honest across husky upgrades: the only
way to pass is to actually be what husky produces.

It also dispatches `h` itself in a synthetic tree, which is the only way to
test the contract our hooks are built on -- the exit code, the 127 message, the
`HUSKY=0` short circuit, `sh -e`, and `node_modules/.bin` on `PATH` -- without
a repository and without risking the real hooks.

Skipped, not failed, without Node or an installed husky, so a Python-only
checkout still runs the rest of the suite.
"""

from __future__ import annotations

import os
import shutil
import subprocess
import sys
from pathlib import Path

import pytest

from scripts.hooks import _runtime as rt

HUSKY_INDEX = rt.REPO_ROOT / "node_modules" / "husky" / "index.js"
GENERATED = rt.REPO_ROOT / ".husky" / "_"

# Runs husky's installer in whatever directory it is started from. The module is
# resolved by absolute path because the cwd has to be the throwaway repo: husky
# checks for `.git` relative to the cwd.
GENERATOR = """
const { pathToFileURL } = await import('node:url')
const husky = await import(pathToFileURL(process.argv[2]).href)
console.log(JSON.stringify(husky.default()))
"""


def _node() -> str:
    node = shutil.which("node")
    assert node is not None
    return node


def _husky_available() -> bool:
    return shutil.which("node") is not None and HUSKY_INDEX.is_file()


pytestmark = pytest.mark.skipif(
    not _husky_available(),
    reason="needs node and an installed husky (npm install)",
)


def _run(command: list[str], cwd: Path) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        command, cwd=str(cwd), capture_output=True, text=True, check=False
    )


@pytest.fixture(scope="module")
def fresh_generated(tmp_path_factory) -> Path:
    """A `.husky/_/` generated from scratch by the installed husky."""
    repo = tmp_path_factory.mktemp("husky-fresh")
    _run(["git", "init", "--quiet"], cwd=repo)
    (repo / "generate.mjs").write_text(GENERATOR, encoding="utf-8")
    result = _run([_node(), "generate.mjs", str(HUSKY_INDEX)], cwd=repo)
    # husky returns '' on success, or a message saying why it did nothing.
    assert result.stdout.strip() == '""', (
        f"husky refused to install into a scratch repo: {result.stdout!r} "
        f"{result.stderr!r}"
    )
    return repo / ".husky" / "_"


def _synthetic_chain(tmp_path: Path, hook_body: str | None) -> Path:
    """A throwaway `.husky/` tree holding husky's real dispatcher and one shim.

    `h` resolves the hook from its own path, so a copied tree behaves exactly
    like the real one while leaving the real one alone.
    """
    generated = tmp_path / ".husky" / "_"
    generated.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(GENERATED / "h", generated / "h")
    shutil.copyfile(GENERATED / "pre-commit", generated / "pre-commit")
    if hook_body is not None:
        (tmp_path / ".husky" / "pre-commit").write_text(hook_body, encoding="utf-8")
    return generated / "pre-commit"


def _dispatch(shim: Path, env: dict[str, str] | None = None) -> subprocess.CompletedProcess[str]:
    """Run a generated shim the way git does, with no ambient husky config.

    The startup file is redirected into the test's own temp space: an
    `init.sh` on the developer's machine can set `HUSKY=0`, which would make
    these assertions depend on who is running them.
    """
    isolated = dict(os.environ)
    isolated["XDG_CONFIG_HOME"] = str(shim.parent.parent.parent / "no-config")
    if env:
        isolated.update(env)
    return subprocess.run(
        ["sh", str(shim)], capture_output=True, text=True, check=False, env=isolated
    )


class TestGeneratedDirMatchesHusky:
    def test_the_checkout_has_a_generated_directory(self):
        assert GENERATED.is_dir(), "run `npm install` (or `npm run hooks:install`)"

    def test_the_same_files_are_generated(self, fresh_generated):
        """A husky upgrade that renames or adds a shim must not go unnoticed."""
        on_disk = {entry.name for entry in GENERATED.iterdir() if entry.is_file()}
        expected = {entry.name for entry in fresh_generated.iterdir() if entry.is_file()}
        assert on_disk == expected, (
            f"only in this checkout: {sorted(on_disk - expected)}; "
            f"only in a fresh install: {sorted(expected - on_disk)}"
        )

    def test_every_file_is_byte_identical(self, fresh_generated):
        """The whole reason to use husky rather than reproduce it is fidelity."""
        differing = []
        for expected in sorted(fresh_generated.iterdir()):
            if not expected.is_file():
                continue
            actual = GENERATED / expected.name
            assert actual.is_file(), f"{expected.name} is missing from .husky/_/"
            if actual.read_bytes() != expected.read_bytes():
                differing.append(expected.name)
        assert differing == [], (
            "generated files differ from a fresh husky install: "
            + ", ".join(differing)
            + " - re-run `npm run hooks:install`"
        )

    def test_the_ignore_file_is_a_single_star(self, fresh_generated):
        """Without it, 17 generated files show up in every ``git status``."""
        assert (GENERATED / ".gitignore").read_bytes() == b"*"
        assert (fresh_generated / ".gitignore").read_bytes() == b"*"

    def test_one_dispatcher_per_hook_husky_knows(self, fresh_generated):
        hooks = {entry.name for entry in fresh_generated.iterdir() if entry.is_file()}
        assert set(rt.HUSKY_HOOKS) <= hooks
        # We ship a subset; the doctor asserts the two sets are equal.
        assert set(rt.HOOKS) <= hooks

    def test_the_deprecation_guard_is_generated(self, fresh_generated):
        """husky overwrites v8's `husky.sh` so stale headers announce themselves.

        A checkout carrying v8's real `husky.sh` would silently support the old
        shim format, which is the migration husky 9 exists to force.
        """
        guard = (GENERATED / "husky.sh").read_text(encoding="utf-8")
        assert "DEPRECATED" in guard
        assert guard == (fresh_generated / "husky.sh").read_text(encoding="utf-8")

    def test_generated_hooks_delegate_to_the_shared_dispatcher(self, fresh_generated):
        for hook in rt.HUSKY_HOOKS:
            text = (GENERATED / hook).read_text(encoding="utf-8")
            assert text == (fresh_generated / hook).read_text(encoding="utf-8")
            # husky writes the shims without a trailing newline; the equality
            # check above is the real assertion, this one pins the delegation.
            assert text.endswith('/h"'), f".husky/_/{hook} does not delegate to _/h"


class TestTheDispatcherContract:
    """The behaviour of `h` that our hooks are built on."""

    def test_a_missing_hook_is_a_silent_no_op(self, tmp_path):
        """No `.husky/<hook>` file means exit 0, not an error.

        An unimplemented hook is therefore harmless -- and silently inert,
        which is exactly why the doctor, not git, is what notices a hook that
        never runs.
        """
        result = _dispatch(_synthetic_chain(tmp_path, None))
        assert result.returncode == 0
        assert result.stdout.strip() == ""

    def test_a_failing_hook_keeps_its_exit_code(self, tmp_path):
        """The exit code is the whole interface: git blocks on it."""
        result = _dispatch(_synthetic_chain(tmp_path, "exit 3\n"))
        assert result.returncode == 3
        assert "pre-commit script failed (code 3)" in result.stdout

    def test_a_missing_command_is_reported_as_a_path_problem(self, tmp_path):
        """127 gets its own message, because it means PATH, not the hook."""
        result = _dispatch(
            _synthetic_chain(tmp_path, "gatekeeper-no-such-command-xyz\n")
        )
        assert result.returncode == 127
        assert "command not found in PATH" in result.stdout

    def test_husky_zero_returns_zero_without_running_the_hook(self, tmp_path):
        """`HUSKY=0` is checked before the hook body, so a broken hook is moot."""
        result = _dispatch(
            _synthetic_chain(tmp_path, "exit 99\n"), env={"HUSKY": "0"}
        )
        assert result.returncode == 0
        assert "script failed" not in result.stdout

    def test_the_hook_body_runs_with_errexit(self, tmp_path):
        """`sh -e`: a failing command aborts the hook rather than being ignored.

        This is why our shims avoid running loose commands in shell -- under
        `-e`, a harmless-looking `grep` that finds nothing ends the hook.
        """
        result = _dispatch(
            _synthetic_chain(tmp_path, "true\nfalse\necho unreachable\n")
        )
        assert result.returncode == 1
        assert "unreachable" not in result.stdout

    def test_node_modules_bin_is_prepended_to_path(self, tmp_path):
        """Upstream's `7_node_modules_path.sh`, at the level of `h` itself."""
        body = 'case ":$PATH:" in *":node_modules/.bin:"*) exit 0 ;; *) exit 7 ;; esac\n'
        result = _dispatch(_synthetic_chain(tmp_path, body))
        assert result.returncode == 0, result.stdout + result.stderr

    def test_a_hook_file_that_is_a_directory_does_not_explode(self, tmp_path):
        """`[ ! -f ]` is a file test, so a directory named like a hook is a no-op."""
        shim = _synthetic_chain(tmp_path, None)
        (tmp_path / ".husky" / "pre-commit").mkdir()
        result = _dispatch(shim)
        assert result.returncode == 0


if sys.platform == "win32" and shutil.which("sh") is None:  # pragma: no cover
    pytest.skip("no sh on PATH", allow_module_level=True)
