#!/usr/bin/env python3
"""prepare-commit-msg hook: warn about protected branches, seed the template.

Git calls this as ``prepare-commit-msg <msgfile> [<source> [<sha>]]`` where
source is one of ``message`` (-m/-F), ``template``, ``merge``, ``squash`` or
``commit`` (amend).

Two things happen:

1. Committing directly to a protected branch is reported, mirroring the
   ``direct_to_main`` rule in .gatekeeper.yml.
2. When an editor is about to open on a fresh message, the allowed commit
   types are appended as comments. This is advisory only.

Comments are added *only* for editor invocations. Git's ``whitespace``
cleanup mode -- which applies to ``-m`` messages -- does not strip comment
lines, so appending there would leak ``#`` lines into the real message.
"""

from __future__ import annotations

import sys

from scripts.hooks import _policy as policy
from scripts.hooks import _runtime as rt
from scripts.hooks.commit_msg import ALLOWED_TYPES

# git commit cleanup modes that keep # lines in the final message.
_KEEPS_COMMENTS = {"verbatim", "whitespace"}

# Sources where an editor opens and git will strip comment lines.
_EDITOR_SOURCES = {"", "template", "commit"}


def _cleanup_mode() -> str:
    code, out = rt.git("config", "--get", "commit.cleanup")
    return out.strip() if code == 0 else ""


def _has_content(text: str) -> bool:
    """True when the message already has a real (non-comment) line."""
    return any(line.strip() and not line.strip().startswith("#") for line in text.splitlines())


def _cheat_sheet(protected_branch: str) -> str:
    lines = [
        "#",
        "# Gatekeeper accepts conventional commit subjects:",
        "#   <type>(<scope>): <subject>",
        f"#   types: {', '.join(ALLOWED_TYPES)}",
    ]
    if protected_branch:
        lines.append(
            f"# You are on protected branch '{protected_branch}' — direct commits "
            "are reported by the direct_to_main rule."
        )
    lines.append("#")
    return "\n".join(lines) + "\n"


def main(argv: list[str]) -> int:
    rt.enter("prepare-commit-msg", argv)
    if rt.skipped("prepare-commit-msg"):
        rt.log(f"{rt.BANNER} prepare-commit-msg skipped via {rt.SKIP_ENV}")
        return 0

    if not argv:
        return 0
    from pathlib import Path

    message_path = Path(argv[0])
    source = argv[1].strip() if len(argv) > 1 else ""
    branch = policy.current_branch()
    protected = branch if policy.is_protected(branch) else ""

    # Merge and squash messages are generated by git; leave them alone.
    if source in {"merge", "squash"}:
        if protected:
            rt.log(
                f"{rt.BANNER} preparing a merge on protected branch '{branch}' "
                "— pre-merge-commit will check this"
            )
        return 0

    if protected:
        rt.log(
            f"{rt.BANNER} committing directly to protected branch '{branch}' "
            f"({policy.CONFIG_FILENAME}: direct_to_main="
            f"{policy.rule_severity('direct_to_main') or 'unset'})"
        )

    if not message_path.exists():
        return 0

    if source not in _EDITOR_SOURCES:
        return 0
    if _cleanup_mode() in _KEEPS_COMMENTS:
        return 0

    text = message_path.read_text(encoding="utf-8")
    if _has_content(text):
        return 0

    with open(message_path, "a", encoding="utf-8") as handle:
        handle.write(_cheat_sheet(protected))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
